server:
  port: 6277
  host: "0.0.0.0"
  mode: "release" # "release" or "debug"

database:
  type: "sqlite"
  path: "data/ech0.db"

setting:
  sitetitle: "Ech0s~"
  servername: "Ech0s~"
  serverurl: "https://ech0.example.com"
  allowregister: true
  icpnumber: ""

upload:
  maxsize: 5242880
  savepath: "data/images/"
  allowedtypes: 
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/jpg"

auth:
  jwt:
    expires: 2592000 # 30天（单位秒）
    issuer: "ech0s"
    audience: "ech0s"
